#include <class/java_opcodes.h>

const std::string opcodes::names[] = {
    ""        , ""        , "iconst_m1", "iconst_0",
    "iconst_1", "iconst_2", "iconst_3", "iconst_4",
    "iconst_5", ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    "bipush"  , "sipush"  , "ldc"     , "ldc_w"   ,
    "ldc2_w"  , "iload"   , ""        , ""        ,
    ""        , "aload"   , "iload_0" , "iload_1" ,
    "iload_2" , "iload_3" , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , "aload_0" , "aload_1" ,
    "aload_2" , "aload_3" , "iaload"  , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , "istore"  , ""        ,
    ""        , ""        , "astore"  , "istore_0",
    "istore_1", "istore_2", "istore_3", ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , "astore_0",
    "astore_1", "astore_2", "astore_3", "iastore" ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , "pop"     ,
    ""        , "dup"     , "dup_x1"  , ""        ,
    ""        , ""        , ""        , ""        ,
    "iadd"    , ""        , ""        , ""        ,
    "isub"    , ""        , ""        , ""        ,
    "imul"    , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    "iinc"    , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , "ifeq"    , "ifne"    , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , "if_icmpge", ""        ,
    "if_icmple", ""        , ""        , "goto"    ,
    ""        , ""        , ""        , ""        ,
    "ireturn" , ""        , ""        , ""        ,
    ""        , "return"  , "getstatic", "putstatic",
    "getfield", "putfield", "invokevirtual", "invokespecial",
    "invokestatic", ""        , ""        , "new"     ,
    "newarray", ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
    ""        , ""        , ""        , ""        ,
};
